[CmdletBinding()]
param(
    [string]$PromptFile = "tests/prompts/PowerBI_Test.md",
    [string]$OutputDir = "tests/results",
    [string]$OutputFileName = "test_results.md",
    [string]$Model = "gpt-4.1",
    [string]$ApiEndpoint = "https://models.inference.ai.azure.com/chat/completions",
    [int]$MaxFileChars = 25000,
    [switch]$IncludeBpaRules,
    [switch]$FailIfNotConfigured
)

$ErrorActionPreference = "Stop"

function Test-ConfiguredValue {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $false
    }

    if ($Value -match "^<.+>$") {
        return $false
    }

    return $true
}

function Get-RelativePath {
    param(
        [Parameter(Mandatory = $true)][string]$BasePath,
        [Parameter(Mandatory = $true)][string]$TargetPath
    )

    $resolvedBase = (Resolve-Path -Path $BasePath).Path
    $resolvedTarget = (Resolve-Path -Path $TargetPath).Path

    if (-not $resolvedBase.EndsWith([IO.Path]::DirectorySeparatorChar)) {
        $resolvedBase = $resolvedBase + [IO.Path]::DirectorySeparatorChar
    }

    $baseUri = New-Object System.Uri($resolvedBase)
    $targetUri = New-Object System.Uri($resolvedTarget)

    return [System.Uri]::UnescapeDataString($baseUri.MakeRelativeUri($targetUri).ToString()).Replace("/", [IO.Path]::DirectorySeparatorChar)
}

function Get-CandidateFiles {
    param([string]$RootPath)

    $extensions = @(".pbip", ".pbir", ".pbism", ".json", ".tmdl")

    return Get-ChildItem -Path $RootPath -Recurse -File | Where-Object {
        $_.Extension -in $extensions -and
        $_.FullName -notmatch "\\tests\\results\\" -and
        $_.FullName -notmatch "\\.git\\" -and
        $_.FullName -notmatch "\\.pbi\\cache\.abf$"
    } | Sort-Object FullName
}

function Get-FilePromptBlock {
    param(
        [Parameter(Mandatory = $true)][string]$RootPath,
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(Mandatory = $true)][int]$MaxChars
    )

    $relativePath = Get-RelativePath -BasePath $RootPath -TargetPath $FilePath
    $content = Get-Content -Path $FilePath -Raw

    if ($content.Length -gt $MaxChars) {
        $content = $content.Substring(0, $MaxChars) + "`n... [TRUNCATED FOR CONTEXT SIZE]"
    }

    return @"
### FILE: $relativePath
```text
$content
```
"@
}

function ConvertTo-ResultText {
    param($ModelContent)

    if ($ModelContent -is [string]) {
        return $ModelContent
    }

    if ($ModelContent -is [System.Array]) {
        $parts = foreach ($item in $ModelContent) {
            if ($null -ne $item.text) {
                $item.text
            }
            elseif ($null -ne $item.content) {
                $item.content
            }
            else {
                $item | Out-String
            }
        }

        return ($parts -join "`n")
    }

    return ($ModelContent | Out-String)
}

function New-SkippedResult {
    param(
        [Parameter(Mandatory = $true)][string]$Reason,
        [Parameter(Mandatory = $true)][string]$PromptPath,
        [Parameter(Mandatory = $true)][string]$OutputTarget
    )

    $generatedUtc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'")

    return @"
# Measure Killer-Style + BPA PBIP Test Results
> WARNING: Overall Risk: MEDIUM

## Executive Summary
- AI markdown test execution was skipped.
- Reason: $Reason
- PBIP context was not evaluated by a model.

## Test Metadata
- generated_utc: $generatedUtc
- mode: skipped
- prompt_file: $PromptPath
- output_target: $OutputTarget

## Scope
### Executed
- Prompt file existence validation
- Output folder preparation

### Not Testable in Local PBIP
- AI inference execution without API credentials

## Summary Metrics
| Metric | Value |
|---|---:|
| ai_execution_performed | 0 |
| finding_count | 1 |

## Severity Summary
| Severity | Count |
|---|---:|
| Critical | 0 |
| High | 0 |
| Medium | 1 |
| Low | 0 |
| Info | 0 |

## Findings (Measure Killer-style)
### [MEDIUM] AI test execution skipped
**Issue:** Model API credentials were not configured.
**Evidence:** Missing GITHUB_MODELS_API_KEY and AZURE_OPENAI_API_KEY.
**Impact:** No AI-generated PBIP assessment was produced.
**Recommendation:** Configure one of the API keys and rerun this test.

## BPA Rules Compliance (Static PBIP Assessment)
Not executed in skipped mode.

## Unified Verdict
Measure Killer-style checks: WARNING
BPA static assessment: NOT_RUN
Combined verdict: WARNING - configure AI test credentials first.

## Appendix
- This output was generated by scripts/run-ai-md-test.ps1 in skipped mode.
"@
}

$workspaceRoot = (Get-Location).Path
$resolvedPromptPath = Join-Path $workspaceRoot $PromptFile

if (-not (Test-Path -Path $resolvedPromptPath)) {
    throw "Prompt file not found: $PromptFile"
}

$resolvedOutputDir = Join-Path $workspaceRoot $OutputDir
$historyDir = Join-Path $resolvedOutputDir "history"
New-Item -ItemType Directory -Force -Path $resolvedOutputDir | Out-Null
New-Item -ItemType Directory -Force -Path $historyDir | Out-Null

$promptText = Get-Content -Path $resolvedPromptPath -Raw
$candidateFiles = Get-CandidateFiles -RootPath $workspaceRoot

$fileBlocks = foreach ($file in $candidateFiles) {
    Get-FilePromptBlock -RootPath $workspaceRoot -FilePath $file.FullName -MaxChars $MaxFileChars
}

$repoContext = ($fileBlocks -join "`n")

$bpaRulesContext = ""
if ($IncludeBpaRules) {
    try {
        $bpaUrl = "https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json"
        $bpaRulesContext = (Invoke-WebRequest -Uri $bpaUrl -UseBasicParsing).Content

        if ($bpaRulesContext.Length -gt 120000) {
            $bpaRulesContext = $bpaRulesContext.Substring(0, 120000) + "`n... [TRUNCATED BPA RULES CONTEXT]"
        }
    }
    catch {
        Write-Warning "Unable to fetch BPA rules. Continuing without BPA rules payload."
    }
}

$apiKey = $env:GITHUB_MODELS_API_KEY
if (-not (Test-ConfiguredValue -Value $apiKey)) {
    $apiKey = $env:AZURE_OPENAI_API_KEY
}

$latestResultPath = Join-Path $resolvedOutputDir $OutputFileName
$historyStamp = (Get-Date).ToUniversalTime().ToString("yyyyMMdd_HHmmss")
$historyResultPath = Join-Path $historyDir ("test_results_" + $historyStamp + ".md")
$latestMetadataPath = Join-Path $resolvedOutputDir "latest_run.json"

if (-not (Test-ConfiguredValue -Value $apiKey)) {
    $missingReason = "No AI API key was found in GITHUB_MODELS_API_KEY or AZURE_OPENAI_API_KEY."

    if ($FailIfNotConfigured) {
        throw $missingReason
    }

    $skippedResult = New-SkippedResult -Reason $missingReason -PromptPath $PromptFile -OutputTarget (Join-Path $OutputDir $OutputFileName)
    Set-Content -Path $latestResultPath -Value $skippedResult -Encoding utf8
    Set-Content -Path $historyResultPath -Value $skippedResult -Encoding utf8

    $skippedMetadata = @{
        generatedUtc = (Get-Date).ToUniversalTime().ToString("o")
        mode = "skipped"
        reason = $missingReason
        promptFile = $PromptFile
        outputFile = (Join-Path $OutputDir $OutputFileName)
        historyFile = (Join-Path $OutputDir ("history/test_results_" + $historyStamp + ".md"))
    }

    Set-Content -Path $latestMetadataPath -Value ($skippedMetadata | ConvertTo-Json -Depth 6) -Encoding utf8
    Write-Host "AI test skipped. Output written to: $latestResultPath"
    exit 0
}

$executionPrompt = @"
You are executing an AI-based PBIP quality test from a markdown prompt.

Important output rule:
- Return only markdown that is intended to be saved in tests/results/test_results.md.
- If the prompt mentions Testing/test_results.md, treat it as tests/results/test_results.md.

Test prompt instructions:
$promptText

Repository context to analyze:
$repoContext
"@

if (-not [string]::IsNullOrWhiteSpace($bpaRulesContext)) {
    $executionPrompt += @"

BPA rules payload (optional context):
```json
$bpaRulesContext
```
"@
}

$requestBody = @{
    model = $Model
    temperature = 0.1
    messages = @(
        @{
            role = "system"
            content = "You are a strict Power BI PBIP QA assistant. Produce deterministic markdown output only."
        },
        @{
            role = "user"
            content = $executionPrompt
        }
    )
}

$headers = @{
    Authorization = "Bearer $apiKey"
    "Content-Type" = "application/json"
}

Write-Host "Executing AI markdown test with model: $Model"
$response = Invoke-RestMethod -Method Post -Uri $ApiEndpoint -Headers $headers -Body ($requestBody | ConvertTo-Json -Depth 20)

if (-not $response.choices -or $response.choices.Count -eq 0) {
    throw "AI API returned no choices."
}

$resultMarkdown = ConvertTo-ResultText -ModelContent $response.choices[0].message.content
if ([string]::IsNullOrWhiteSpace($resultMarkdown)) {
    throw "AI API returned empty content."
}

Set-Content -Path $latestResultPath -Value $resultMarkdown -Encoding utf8
Set-Content -Path $historyResultPath -Value $resultMarkdown -Encoding utf8

$runMetadata = @{
    generatedUtc = (Get-Date).ToUniversalTime().ToString("o")
    mode = "executed"
    model = $Model
    promptFile = $PromptFile
    candidateFileCount = $candidateFiles.Count
    outputFile = (Join-Path $OutputDir $OutputFileName)
    historyFile = (Join-Path $OutputDir ("history/test_results_" + $historyStamp + ".md"))
    includeBpaRules = [bool]$IncludeBpaRules
}

Set-Content -Path $latestMetadataPath -Value ($runMetadata | ConvertTo-Json -Depth 6) -Encoding utf8

Write-Host "AI test completed successfully."
Write-Host "Latest output: $latestResultPath"
Write-Host "History output: $historyResultPath"
