<#
.SYNOPSIS
    Claude Code PreToolUse hook - blocks writes to paths an agent must never author.

.DESCRIPTION
    Denies Write/Edit/NotebookEdit against:
      Proposals/            commercial client material, gitignored, never a deliverable input
      **/.pbi/              Power BI Desktop cache and local settings, machine-specific
      tests/screenshots/    generated by the verification loop, overwritten every run
      .claude/.pbip-state/  hook bookkeeping; hand-editing it corrupts the fix budget

    This is a guardrail, not a sandbox: it sees Write/Edit only, so shell
    redirection through Bash or PowerShell goes straight past it.

    Exit 2 blocks the call and hands stderr back to the agent. Anything
    unexpected exits 0 - a broken guard must not stop work.
#>

$ErrorActionPreference = "Stop"

try {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { exit 0 }

    $hookInput = $null
    try { $hookInput = $raw | ConvertFrom-Json } catch { exit 0 }
    if (-not $hookInput -or -not $hookInput.tool_input) { exit 0 }

    $ti = $hookInput.tool_input
    $target = $null
    foreach ($k in @('file_path', 'notebook_path', 'path')) {
        if ($ti.PSObject.Properties.Name -contains $k -and -not [string]::IsNullOrWhiteSpace($ti.$k)) {
            $target = $ti.$k; break
        }
    }
    if (-not $target) { exit 0 }

    $repoRoot = $env:CLAUDE_PROJECT_DIR
    if ([string]::IsNullOrWhiteSpace($repoRoot)) {
        $repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..")).Path
    }

    # Normalise to a repo-relative, forward-slashed path so the rules below read plainly.
    try { $full = [System.IO.Path]::GetFullPath($target) } catch { exit 0 }
    try { $rootFull = [System.IO.Path]::GetFullPath($repoRoot).TrimEnd('\') } catch { exit 0 }

    if (-not $full.StartsWith($rootFull, [System.StringComparison]::OrdinalIgnoreCase)) { exit 0 }
    $rel = $full.Substring($rootFull.Length).TrimStart('\', '/').Replace('\', '/')
    if ([string]::IsNullOrWhiteSpace($rel)) { exit 0 }

    $reason = $null
    if ($rel -match '^(?i)Proposals/') {
        $reason = "Proposals/ holds commercial client material. It is gitignored and is never an input to or output of a deliverable."
    } elseif ($rel -match '(?i)(^|/)\.pbi/') {
        $reason = "**/.pbi/ holds Power BI Desktop's local cache and settings. It is machine-specific, gitignored, and rewritten by Desktop."
    } elseif ($rel -match '^(?i)tests/screenshots/') {
        $reason = "tests/screenshots/ is generated by the verification loop and overwritten on every run. Fix the PBIR/TMDL source instead - never the PNG."
    } elseif ($rel -match '^(?i)\.claude/\.pbip-state/') {
        $reason = "'.claude/.pbip-state/' is the Stop hook's bookkeeping. Editing it corrupts change detection and the fix budget."
    }

    if ($reason) {
        [Console]::Error.WriteLine("BLOCKED write to $rel")
        [Console]::Error.WriteLine($reason)
        exit 2
    }

    exit 0

} catch {
    # Fail open. A guard that errors must not become a wall.
    exit 0
}
